/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-06 07:55:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.wildflower;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dictionary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/wildflower/header.jsp", Long.valueOf(1482394836000L));
    _jspx_dependants.put("/wildflower/footer.jsp", Long.valueOf(1481619576000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Wild Flower</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3-theme-red.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"max-width:600px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header부분 -->\r\n");
      out.write("<header>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>HEADER</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3-theme-red.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- sid nav 부분 -->\r\n");
      out.write("<nav class=\"w3-sidenav w3-card-2 w3-white w3-top\" style=\"width:40%;display:none;z-index:2\" id=\"mySidenav\">\r\n");
      out.write("<div class=\"w3-container w3-theme-d2\">\r\n");
      out.write("  <span onclick=\"w3_close()\" class=\"w3-closenav w3-right w3-xlarge\">x</span>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"w3-padding w3-center\">\r\n");
      out.write("     ");

        // 현재 로그인된 아이디가 없다면 (= session에 저장된 id가 없다면)
        if(session.getAttribute("id") == null) {
            
      out.write("\r\n");
      out.write("            <img class=\"w3-circle\" src=\"../image/user.png\" alt=\"user\" style=\"width:40%\">\r\n");
      out.write("  \t<br><br> Login을 해주세요.<br>\r\n");
      out.write(" \t\t<button class=\"w3-btn w3-white w3-border w3-small w3-slim w3-round-large\" onclick=\"location.href='../wildflower/loginForm.jsp'\">\r\n");
      out.write(" \t\t\t<i class=\"fa fa-key\"></i> Login \r\n");
      out.write(" \t\t</button>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t<button class=\"w3-btn w3-white w3-border w3-small w3-slim w3-round-large\" onclick=\"location.href='../wildflower/joinForm.jsp'\">\r\n");
      out.write(" \t\t\t<i class=\"fa fa-send-o\"></i> &nbsp;  join \r\n");
      out.write(" \t\t</button>\r\n");
      out.write("            ");

        } 
        // 현재 로그인된 아이디가 있다면 (= session에 저장된 id가 있다면)
        else {
        
            
      out.write("\r\n");
      out.write("            <img class=\"w3-circle\" src=\"../image/user.png\" alt=\"user\" style=\"width:40%\">\r\n");
      out.write("  \t\t\t<br><br> ");
 out.println(session.getAttribute("id") + " 님 환영합니다"); 
      out.write("<br>\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t<button class=\"w3-btn w3-white w3-border w3-small w3-slim w3-round-large\" onclick=\"location.href='../wildflower/myInfo.jsp'\">\r\n");
      out.write(" \t\t\t<i class=\"fa fa-star\"></i> 내정보수정\r\n");
      out.write(" \t\t</button>\r\n");
      out.write("\t\r\n");
      out.write(" \t\t<button class=\"w3-btn w3-white w3-border w3-small w3-slim w3-round-large\" onclick=\"location.href='../wildflower/logout.jsp'\">\r\n");
      out.write(" \t\t\t<i class=\"fa fa-sign-out\"></i> Logout \r\n");
      out.write(" \t\t</button>\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\r\n");
      out.write("            ");

        }
    
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("\t <h3><i class=\"fa fa-tree\"></i> Menu </h3></div>\r\n");
      out.write("\t  <a href=\"../wildflower/index.jsp\">Home</a>\r\n");
      out.write("\t  <a href=\"../noticeboard/notice.jsp\">공지사항</a>\r\n");
      out.write("\t  <a href=\"../wildflower/dictionary.jsp\">야생화 사전</a>\r\n");
      out.write("\t  <a href=\"../wildflower/gallery.jsp\">야생화 갤러리</a>\r\n");
      out.write("\t  <a href=\"../freeboard/freeboard.jsp\">자유게시판</a>\r\n");
      out.write("\t  <a href=\"../qnaboard/qna.jsp\">이름이뭐에요?</a>\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("<!-- \t  <a href=\"../wildflower/test.jsp\">이름이뭐에요?</a> -->\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"w3-container\">\r\n");
      out.write("\t  <h3> <i class=\"fa fa-bookmark\"></i>  BookMark</h3></div>\r\n");
      out.write("\t  <a href=\"http://www.naver.com\" target=\"_blank\">NAVER</a>\r\n");
      out.write("\t  <a href=\"http://www.google.co.kr\" target=\"_blank\">구글</a>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- headerbar부분 -->\r\n");
      out.write("<header class=\"w3-container w3-card-4 w3-theme w3-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h2>\r\n");
      out.write("\t  <i class=\"w3-opennav fa fa-bars\" onclick=\"w3_open()\"></i>\r\n");
      out.write("\t  &nbsp;&nbsp;\r\n");
      out.write("\t  <b>Wild Flower</b>\r\n");
      out.write("\t  <a href=\"../wildflower/index.jsp\"><i class=\"fa fa-home w3-padding w3-display-right\"></i></a>\r\n");
      out.write("  </h2>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- contents 부분 -->\r\n");
      out.write("<div class=\"w3-container\" style=\"margin-top:75px\">\r\n");
      out.write("\t<h3 class=\"w3-text-red\">\r\n");
      out.write("\t<img src=\"../image/daisy.png\" height=\"20px\" width=\"20px\"/>야생화 사전</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<span class=\"w3-third w3-padding-small\" >\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"w3-input w3-border w3-padding-0 w3-round-small\" placeholder=\" Search..\">\r\n");
      out.write("\t\t</span> \r\n");
      out.write("\t\t<i class=\"fa fa-search w3-padding-8\"></i> \r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"w3-row\">\r\n");
      out.write("\t  <div class=\"w3-col s3\">\r\n");
      out.write("\t    <img src=\"../image/flower/d1.jpg\" style=\"width:100%\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"w3-col s9 w3-container\">\r\n");
      out.write("\t    <h3 class=\"w3-text-red\">해국 </h3>\r\n");
      out.write("\t    <ul>\r\n");
      out.write("\t    \t<li>학명: Aster sphathulifolius Maxim</li>\r\n");
      out.write("\t    \t<li>분류: 국화과</li>\r\n");
      out.write("\t    \t<li>크기: 30~60cm</li>\r\n");
      out.write("\t    \t<li>용도: 관상용</li>\r\n");
      out.write("\t    \t<li>개화시기: 7월~11월 초, 고산지 및 지리산 개화기(8~11월 초)</li>\r\n");
      out.write("\t    \t<li>분포지: 한국</li>\r\n");
      out.write("\t    \t<li>생육특성: 우리나라 중부 이남의 해변에서 자라는 다년생 초본이다. 생육환경은 햇볕이 잘 드는 암벽이나 경사진 곳에서 자란다. 키는 30~60cm이고, 잎은 양면에 융모가 많으며 어긋난다. 잎은 위에서 보면 뭉치듯 전개되고 잎과 잎 사이는 간격이 거의 없는 정도이다. 겨울에도 상단부의 잎은 고사하지 않고 남아 있는 반상록 상태다. 꽃은 연한 자주색으로 가지 끝에 하나씩 달리고 지름은 3.5~4cm이다.\r\n");
      out.write("\t\t\t잎은 풍성하게 많으며 끈적거리는 감이 있어서 여름철에 애벌레가 많이 꼬인다.</li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class=\"w3-row\">\r\n");
      out.write("\t  <div class=\"w3-col s3\">\r\n");
      out.write("\t    <img src=\"../image/flower/d2.jpg\" style=\"width:100%\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"w3-col s9 w3-container\">\r\n");
      out.write("\t    <h3 class=\"w3-text-red\">털머위</h3>\r\n");
      out.write("\t    <ul>\r\n");
      out.write("\t    \t<li>학명: Farfugium japonicum (L.) Kitam</li>\r\n");
      out.write("\t    \t<li>분류: 국화과</li>\r\n");
      out.write("\t    \t<li>크기: 30~50cm</li>\r\n");
      out.write("\t    \t<li>용도: 관상용</li>\r\n");
      out.write("\t    \t<li>개화시기: \t9월~10월, 고산지 및 지리산 개화기(10~11월 초)</li>\r\n");
      out.write("\t    \t<li>분포지: 한국</li>\r\n");
      out.write("\t    \t<li>생육특성: 우리나라 남부와 제주도 울릉도 해안에서 나는 상록 다년생 초본이다. 생육환경은 양지 혹은 반그늘의 따뜻하고 물 빠짐이 좋은 곳에 자란다. 키는 30~50cm이고, 잎은 길이 4~15cm, 폭 6~30cm로 광택이 많이 난다. 꽃은 황색이며 길이 30~75cm로 포가 있으며 가지 끝에 지름 4~6cm 정도되는 꽃이 한 개씩 달려서 전체적으로 큰 무리를 이룬다. 열매는 11~12월경에 맺고 흑갈색에 길이는 0.8~1.1cm로 갓털이 있다.</li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class=\"w3-row\">\r\n");
      out.write("\t  <div class=\"w3-col s3\">\r\n");
      out.write("\t    <img src=\"../image/flower/d3.jpg\" style=\"width:100%\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"w3-col s9 w3-container\">\r\n");
      out.write("\t    <h3 class=\"w3-text-red\">투구꽃</h3>\r\n");
      out.write("\t     <ul>\r\n");
      out.write("\t    \t<li>학명: Aconitum jaluense Kom. subsp. Jaluense</li>\r\n");
      out.write("\t    \t<li>분류: 미나리아재비과</li>\r\n");
      out.write("\t    \t<li>크기: 1m</li>\r\n");
      out.write("\t    \t<li>용도: 관상용</li>\r\n");
      out.write("\t    \t<li>개화시기: 8월~9월, 고산지 및 지리산 개화기(9~10월)</li>\r\n");
      out.write("\t    \t<li>분포지: 한국</li>\r\n");
      out.write("\t    \t<li>생육특성: 우리나라 각처의 산에서 자라는 다년생 초본이다. 생육환경은 반그늘 혹은 양지의 물 빠짐이 좋은 곳에서 자란다. 키는 약 1m 정도이고, 잎은 잎자루 끝에서 손바닥을 편 모양으로 3~5갈래로 깊이 갈라지고, 어긋난다. 꽃은 자주색 혹은 흰색으로 모양은 고깔이나 투구와 같으며 줄기에 여러 개의 꽃이 어긋나고 아래에서 위로 올라가며 핀다. 열매는 10~11월에 맺고 타원형이며 뾰족한 암술대가 남아 있다.</li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- footer부분 -->\r\n");
      out.write("<footer class=\"w3-container w3-theme w3-bottom\">\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"w3.css\">\r\n");
      out.write("<title>FOOTER</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"max-width:400px\">\r\n");
      out.write("  <div class=\"w3-container w3-theme\"  style=\"text-align: center;\">\r\n");
      out.write("  \r\n");
      out.write("\t      <a href=\"https://www.facebook.com\"><i class=\"fa fa-facebook  w3-xlarge\" style=\"font-size:40px;color:white\"></i></a>\r\n");
      out.write("          <a href=\"https://twitter.com\"><i class=\"fa fa-twitter w3-xlarge\" style=\"font-size:40px;color:white\"></i></a>\r\n");
      out.write("          <a href=\"www.instagram.com\"><i class=\"fa fa-instagram w3-xlarge\" style=\"font-size:40px;color:white\"></i></a>\r\n");
      out.write("          <br />\r\n");
      out.write("          <b>관리자</b>  ");
      out.print(application.getInitParameter("ceo") );
      out.write("  | \r\n");
      out.write("          <b>Email</b>  ");
      out.print(application.getInitParameter("email") );
      out.write(" <br>\r\n");
      out.write("          <b>Address</b>  ");
      out.print(application.getInitParameter("address") );
      out.write(" |\r\n");
      out.write("          <b>Tel.</b>  ");
      out.print(application.getInitParameter("tel") );
      out.write(" | Copyright (c) 2016 WildFlower <br/>\r\n");
      out.write("  </div>   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function w3_open() {\r\n");
      out.write("    document.getElementById(\"mySidenav\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("function w3_close() {\r\n");
      out.write("    document.getElementById(\"mySidenav\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
